### ISSUE TITLE
testServer send string from external client MessageReceived not fired

### ISSUE THREAD

**Issue by ellLazar** [jchristn/WatsonTcp#10]
Hello,
testserver,

tried to send string from external application , to testServer on same  local pc
the MessageReceived not fired
 
the connect and disconnect from client side where detected correctly

**Comment by jchristn** [comment]
Hi @ellLazar please share your code so I can take a look.  Thanks!

**Comment by ellLazar** [comment]
I tested my client code with other C# TCP server I got also from github,
the send receive string where ok.
but the disconnect implementation did not work, there for I tried yours.
anyway my code is very simple :
 use device Write "ABCD Line 1",!
...
I should get it on server side.

**Comment by jchristn** [comment]
Hi @ellLazar there is no flush character, WatsonTcp takes care of the flush and message framing for you.  Please post a gist with the actual code so I can test it on my side.  Thanks!

**Comment by ellLazar** [comment]
the language I use in client is not C# , it's called Cache intersystems
the connect/disconnect tests I made worked ok with your code,
what remain just to send the string, the serv er accept string ? or maybe stream ?

**Comment by jchristn** [comment]
Oh, that explains it.  WatsonTcp has its own framing mechanism, so you'd need to use WatsonTcp for both the client and the server.  The messages come through with the structure len:data where len is an integer, followed by a colon, then the data as a byte array.  So, "Hello World!" would be sent over the wire as 12:Hello World!  That's why it won't work with a regular TCP client unless you add the framing in.  This is done to ensure complete messages are received on both sides.

**Comment by ellLazar** [comment]
ok now I get response 
use device write "12:Hello World!",! 
please note on the ! char without it the server don't get the message
now I got in server side:
*** MessageReadAsync malformed message from 127.0.0.1:13293 (message header not an integer)
i made also 13: ... to include the ! flush, but got same message

**Comment by jchristn** [comment]
I'd need to see a packet capture of what is on the wire to determine what your TCP client is sending exactly.  Thanks
