### ISSUE TITLE
SSL Question (Problem?) - AuthenticateAsClient 

### ISSUE THREAD

**Issue by Motridox** [jchristn/WatsonTcp#121]
Hello,

I'm porting my project over to use SSL. I'm new to this topic, i searched quite a few hours now and I do not find any information that fits my question.

So I hope I can ask them here.

1) In development you shall use self signed certificates, once you go live, do you need a signed ssl certificate? 
Also If I'm not mistaken I will need my own domain for the certificate?
- Or is there any downsite if we use self signed certificates?

2) I played a bit around with self signed ssl certificates and trusting the certs locally on my machine. Now for my understanding, the server needs to have the pfx cert that includes the private and public keys. once I go live again, I do not ship the pfx file with the tcp client right? They do only need a public certificate? 

3) Once the server is up with my self signed cert, i can connect with the client (same pfx file as the server). But as soon as I change the pfx to a different pfx file (ex: The test.pfx inside WatsonServer) and I can still connect to the server? Shouldn't the server drop the connection because the client is using a different ssl certificate?

4) Inside watson client, the method SslStream.AuthenticateAsClient gets invoked with the first argument beeing the server ip. Shouldn't that argument be equal to the CN= of the certificate? so we should be able to define that string in the WatsonClient constructor

**Comment by jchristn** [comment]
Hi @Motridox thanks for your note.  

You don't need to use a signed certificate from a CA as long as the underlying operating system can verify the validity of the certificate.  So, if you install the self signed certificate in both client and server you should be fine.

I would always recommend using one signed from a CA because then you generally remove the dependency of peers not being able to validate the cert.

You don't need to ship the cert with the client as long as the client trusts the server cert.  This may require that you install the certificate in the client machine, though.  You can also set ```AcceptInvalidCertificates``` to true in the client settings, which will ignore SSL certificate validation problems.

If you are planning to use mutual authentication, you'll need a certificate on both sides (client and server), and, both sides will need to trust/validate the other side, i.e. a cert signed by a CA that both agree is trustworthy, or, the other's cert installed locally and considered trustworthy.

Hope this helps, Joel

**Comment by jchristn** [comment]
Hi @Motridox please re-open if any issues.  Thanks
