### ISSUE TITLE
why the DataReceiver() need A readLocked in WatsonTcpClient

### ISSUE THREAD

**Issue by zc910704** [jchristn/WatsonTcp#127]
I try to learn the skills you dealing with the data read. I found DataReceiver() use a bool readLocked to record the _ReadLock.WaitAsync() result. 
`
readLocked = await _ReadLock.WaitAsync(10, _Token).ConfigureAwait(false);
                        if (readLocked) break;
`
can i just do in ways just like this
`
await _ReadLock.WaitAsync(_Token).ConfigureAwait(false); 
`
just like
`
async () =>
{
    lock(_lockObj) /*I know cant write like this */
   {
     do some stuff
   }
}
`
will it cause any problem?

**Comment by jchristn** [comment]
The problem is that ```WaitAsync``` will only return true if it's able to enter.  I don't know the internals and why it could return ```false``` for reasons other than a timeout.  Theoretically *yes* it could be written the way you mention, assuming there are no other reasons for it to return ```false``` other than a timeout.

This is a great suggestion that could improve performance and reduce code complexity a little bit.  I'll take a note to look into it, and if you have any references that would be helpful, I'd love to see them!

Thanks!  Joel

**Comment by jchristn** [comment]
Looks like it may be safe for me to remove this:

.NET Framework: https://referencesource.microsoft.com/#mscorlib/system/threading/SemaphoreSlim.cs
.NET/.NET Core: https://source.dot.net/#System.Private.CoreLib/SemaphoreSlim.cs,d57f52e0341a581f

In both cases, false is only returned on timeout.  

I'll add it to the list and make sure it works after the change before publishing a new version.  Thanks for pointing this out!

**Comment by zc910704** [comment]
Thanks for take me to the internal of .net . I learn a lot.

**Comment by jchristn** [comment]
Fixed in v4.8.1: https://github.com/jchristn/WatsonTcp/commit/75f1ce23bb044fb55002b4e91cf27bafe90c9deb
and https://www.nuget.org/packages/WatsonTcp/4.8.1

Thanks!
