### ISSUE TITLE
Disconnect reason for authentication

### ISSUE THREAD

**Issue by Jyck** [jchristn/WatsonTcp#145]
with AuthenticationEnabled you get a instand unknown disconnect if you send to server **before** the AuthenticationSucceeded event fired.

so here you get a disconnect because we send a message before auth event.

```
TcpClient.Connect();
if (TcpClient != null && TcpClient.Connected)
    TcpClient.Send(data, meta);
```
            
[WatsonTcpClient] connecting with SSL to 192.168.2.170:59141
[WatsonTcpClient] connected to 192.168.2.170:59141
 --> Send is here
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete {"s":"AuthRequired","len":0}
[WatsonTcpClient] authentication required by server; please authenticate using pre-shared key
[WatsonMessage] non-graceful termination by peer
[WatsonTcpClient] disconnect detected

with waiting for AuthenticationSucceeded event and then send the first messages to server you get:
[WatsonTcpClient] connecting with SSL to 192.168.2.170:59141
[WatsonTcpClient] connected to 192.168.2.170:59141
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete {"s":"AuthRequired","len":0}
[WatsonTcpClient] authentication required by server; please authenticate using pre-shared key
[WatsonMessage] found header demarcation
[WatsonMessage] header processing complete{"s":"AuthSuccess","len":25}
[WatsonTcpClient] authentication successful
 --> Send is here and working

it is logical and not an error, but if you do not recognize it, the reason for the disconnect is difficult to find.
maybe you have an idea to some error message,  or a new public bool Authenticated { get; private set; }

**Comment by jchristn** [comment]
Hi @Jyck are you sure the disconnection was caused by the authentication failure?  When the server receives a message from an unauthenticated client, it sends back a message with status ```AuthRequired``` but does not close the connection.  It an incorrect preshared key is provided, a message with status ```AuthFailure``` is returned but again the connection is not closed.

Similarly on the client, receipt of ```AuthRequired``` invokes the ```AuthenticationRequested``` callback, but does not close the connection.  

You'll find these behaviors in the ```DataReceiver``` methods on both client and server:
- Client: https://github.com/jchristn/WatsonTcp/blob/23fd24293ef94a8b6989f7a91bb4ac9fc4cae543/WatsonTcp/WatsonTcpClient.cs#L752
- Server: https://github.com/jchristn/WatsonTcp/blob/23fd24293ef94a8b6989f7a91bb4ac9fc4cae543/WatsonTcp/WatsonTcpServer.cs#L1029

I'm thinking perhaps something else terminated the connection?

**Comment by Jyck** [comment]
Hi @jchristn the Auth was not failed, it was just in progress while the
first message arrives.
I'm not really sure and make some more tests later. But the solution was to
delay the first message to the server after the Auth success

**Comment by jchristn** [comment]
Interesting.  The message that was sent prior to the auth response should not have disconnected.  It should have responded with an ```AuthRequired``` and kept the connection open.  Can you reliably reproduce this?

**Comment by Jyck** [comment]
Yes I can reproduce it with changing a few lines. I try to get more details
or log details.  I can send you also my client class with the working and
not working code

**Comment by Jyck** [comment]
ok you can reproduce it also with the winform samples.

- add a preshared key to the server.
- add Callbacks.AuthenticationRequested to the client
everything is working.

now send a message before auth was done and you get instant the disconnect.
```
    private void button1_Click(object sender, EventArgs e)
        {
            _Client.Connect();
            _Client.Send("i was send before auth was done");
        }

```

Server Log
```
[Debug    ] Click 'Start' to start the server.
[Info     ] [WatsonTcpServer] starting on 127.0.0.1:9000
[Debug    ] Leaving bStart_Click
[Debug    ] [WatsonTcpServer] accepted connection from 127.0.0.1:62489
[Debug    ] [WatsonTcpServer] requesting authentication material from 127.0.0.1:62489
[Debug    ] [WatsonTcpServer] starting data receiver for 127.0.0.1:62489
[Debug    ] Client 127.0.0.1:62489 connected
[Debug    ] [WatsonTcpServer] message received from unauthenticated endpoint 127.0.0.1:62489
[Warn     ] [WatsonTcpServer] no authentication material for 127.0.0.1:62489
[Debug    ] [WatsonTcpServer] disconnect detected for client 127.0.0.1:62489
[Debug    ] Client 127.0.0.1:62489 disconnected: Normal
[Debug    ] [WatsonTcpServer] client 127.0.0.1:62489 disconnected
```

Client Log
```
[Info     ] [WatsonTcpClient] connecting to 127.0.0.1:9000
[Debug    ] 127.0.0.1:9000 connected
[Info     ] [WatsonTcpClient] connected to 127.0.0.1:9000
[Info     ] [WatsonTcpClient] authentication required by server; please authenticate using pre-shared key
[Info     ] [WatsonTcpClient] authentication required by server; please authenticate using pre-shared key
[Debug    ] [WatsonTcpClient] disconnect detected
[Debug    ] [WatsonTcpClient] data receiver terminated for 127.0.0.1:9000
[Debug    ] 127.0.0.1:9000 disconnected: Normal
```

**Comment by jchristn** [comment]
Hi @Jyck sorry it took me so long to get back to you.  We moved and had other (positive) life activities happening in the past month.  I will look into this ASAP.  Thanks!

**Comment by jchristn** [comment]
Ok - so the reason this is happening is that a message is arriving without validation authentication.  The message contains data that never gets read, meaning, when the server DataReceiver loop continues, it's expecting to find the start of a new message, but there's data from the past message waiting to be read in the stream.  

I'm going to change the behavior such that on authentication failure, the server proactively disconnects and disposes the client rather than leaving the connection in-tact.  Leaving it in-tact actually creates a DoS vulnerability in that anyone could connect and just keep firing messages at the server.

**Comment by jchristn** [comment]
Hi @Jyck please check out the following and re-open if any issues.  Thanks for filing this!

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.10
Commit: https://github.com/jchristn/WatsonTcp/commit/f7d1242fc93ec882f4f857e29acb14841616c180
