### ISSUE TITLE
KeepAlive default values

### ISSUE THREAD

**Issue by zsolt777** [jchristn/WatsonTcp#146]
Hi @jchristn!

I had strange server disconnected events on WIFI, so I started to investigate it using Wireshark. There were tons of keepalive packets because the default value for KeepAliveInterval is 5 milliseconds instead of 5 seconds as you wrote in the readme (and in the code summary).

Would you be so kind to change the description from second to millisecond for both TcpKeepAliveTime and TcpKeepAliveInterval?

Cheers,
Zsolt

**Comment by jchristn** [comment]
Hi @zsolt777 thanks for letting me know!  I appreciate it.  Taking a look now.

**Comment by jchristn** [comment]
Hi @zsolt777 I assume you are using .NET Framework?  

For reference: 
The documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=net-5.0) indicates that it is in seconds.  This is for .NET 5.0.  The same is true for .NET Core 3.1 [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netcore-3.1)

For .NET Framework, ```IOControlCode.KeepAliveValues``` is supposed to align with [RFC 1122 section 4.2.3.6](https://datatracker.ietf.org/doc/html/rfc1122#page-101).  I can't find anything authoritative that the byte array passed in should reflect milliseconds vs seconds, however, all of the sample code indicates that it's milliseconds.

Could you confirm the above?  Cheers, Joel

**Comment by jchristn** [comment]
Ok - I had to leave the keepalive values in seconds, since this is what .NET Core/.NET 5 expect.  The internals will now automatically convert to milliseconds.  This is fixed in v4.8.7, which I'm uploading to NuGet now.  

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.7
Commit: https://github.com/jchristn/WatsonTcp/commit/4ba764fecf1c40acbca38778e011785f7e3cda50

Please re-open if any issues!
