### ISSUE TITLE
Message is not received fully

### ISSUE THREAD

**Issue by SaddamBInSyed** [jchristn/WatsonTcp#27]
When I sent a xml file from telnet then i am not receiving the data in the TCP server side.

Then i checked the code and came to know that THIS TCP SERVER CODE ONLY WORK WITH WATSON TCP CLIENT.

Is there any way to use this WaTSON TCP SERVER code with outside work TCP client apps ( telnet, tera term other TCP client code?

please advise..

**Comment by jchristn** [comment]
Hi @SaddamBInSyed - the reason for this is that TCP provides no message framing whatsoever.  The whole purpose of this project is to provide a client and server that provide message level delivery.  TCP on its own doesn't do that, it's simply a stream and is unaware of message boundaries.  Watson encapsulates messages into a structure so that the client and server apps don't have to be concerned with when/where to start/stop reading/writing.  It's a pretty big problem for TCP-based apps.

If you want something like Watson that will work with Telnet (and aren't concerned about message framing) then check out https://github.com/jchristn/SimpleTcp - also on NuGet - https://www.nuget.org/packages/SuperSimpleTcp.

**Comment by SaddamBInSyed** [comment]
Thank for valuable advice.
