### ISSUE TITLE
Intellisense not showing Comments

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#33]
I had mentioned this on the other discussion, but I'm just adding it here as an item for you to look into.

I double-checked.  I've added Watson via Nuget, and Intellisense comments don't show up for any of the Watson types or methods.   Other Nuget libraries in my project seems to be working fine.

**Comment by jchristn** [comment]
Hi @pha3z - thanks for doing this.  I believe I've resolved it with the latest NuGet update.  It turns out I neglected to check the box next to "XML documentation file" in project properties - build.  Closing this now, please reopen if this doesn't resolve the issue!  

(time to now fix this for every other project!)

**Comment by pha3z** [comment]
Confirmation: Yes this is fixed now.  :)  Thank you!
