### ISSUE TITLE
What does SendAsync() actually do?

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#34]
Now that I've had to do a lot of digging on the implications of Async(), I've got more questions.

According to the MSDN doc on TcpClient, all you need to do to send data is write to the NetworkStream.  The document does not explicitly state this...BUT: that *should* be a non-blocking operation, because the client itself should be reading on a separate thread.

That being said... what value is there in a SendAsync() method?  I would expect Watson's send method does nothing more than write to the underlying network stream.  There shouldn't be any reason to do that asynchronously because there's no need to await such a fast operation.

Is my understanding of the mechanics incorrect?

**Comment by jchristn** [comment]
Hi James, yes indeed, reads and writes are happening on separate threads.  There's a lock to ensure multiple threads aren't writing concurrently (I know that wasn't part of your question).  Yes you are correct, Watson will manage writing to the underlying network stream on your behalf.

There are a couple of reasons for having ```Send``` and ```SendAsync```.  

The first is easy and low-hanging fruit: convenience.  Some people have yet to start the transition to an async model which can often spread like a zombie throughout the codebase.  It's usually a larger change to adopt that model, so having distinct and separate methods helps better support both cases.  If I only had ```SendAsync```, developers would be forced to suppress warnings and use ```.Result``` which people generally do not like to do.

Generally speaking the call to ```NetworkStream.Write``` should *not* be blocking, but based on the way TCP works, that may not always be the case.  If the amount of data outstanding (unacknowledged by the other socket) on the network is too great (window exhaustion), one should assume that writing to the NetworkStream would block since bufferspace/memory is not available to receive the data from the application attempting the write (the other socket hasn't acknowledged it, so the local socket keeps it buffered).  

There shouldn't be a functional behavior difference between ```NetworkStream.Write``` and ```NetworkStream.WriteAsync``` in the above scenario.  What would potentially be very different is in the consequence.  I've generally found that blocking operations in non-async methods (such as ```NetworkStream.Write```) tend to be less friendly and less optimized and often result in higher CPU utilization and other side effects.  This doesn't happen in the async case.

Hope this helps!  Cheers, Joel

**Comment by pha3z** [comment]
Wow.  I didn't see any of these issues mentioned in NetworkStream.Write.   Well I will definitely use SendAsync().  Thank you!
