### ISSUE TITLE
Empty PSH/ACK sent by client before sending actual data?

### ISSUE THREAD

**Issue by pha3z** [jchristn/WatsonTcp#45]
I am attempting to use Watson Server to receive connections from a 3rd party TCP Client.

When I use Watson Client to connect to Watson Server, Data Receive events on the server work fine.  But when the 3rd-party TCP Client connects and sends data to Watson Server, Watson's Data Receive event appears to never fire.

So I got out Wireshark and noticed something different in the packet traffic.  When I send data from Watson Client, it first sends a PSH, ACK packet to the server, and the server responds with an ACK.... and THEN it sends the actual data packet.  The 3rd party TCP client does not do the precursor packet transaction.  The 3rd party just sends its data as soon as it wants to.

So Question 1:  Why does Watson Client send an empty packet with a PSH,ACK and wait for a response before sending the actual data?  This already seems like an unnecessary round trip.

Question 2: Is Watson Server depending on this behavior?  If so, that would explain why its not alerting me when it gets an unexpected data packet from the other system's client.

**Comment by jchristn** [comment]
Hi @pha3z is your third-party sender adhering to the framing structure used by Watson?  That's one reason that comes to mind why it might not be firing.

In terms of why there would be a PSH/ACK, this may be an artifact of how messages are sent.  First, the header is constructed and written to the underlying network stream.  Then, the stream containing the message data is written to the underlying network stream.  Typically each of these writes results in the PSH flag being set.

PSH is really irrelevant in this case as it's nothing more than an indication that the data can be moved into the application receive buffer.  The application is just going to read from it as a stream anyway, and if the data is not in the application receive buffer (because of a lack of a PSH) the stream read forces a call further down the stack.  

I'd be more concerned about the 3rd-party client adhering to the framing used by Watson.

If you need something *without* framing, i.e. write 100 bytes and 100 bytes comes out the other end, you may want to check out my library SimpleTcp (https://github.com/jchristn/simpletcp).  SimpleTcp is like Watson, but without framing, meaning it's compatible with any TCP client/server.  The downside is, of course, that TCP is stream-based, and if you don't use some kind of framing, you have to write your own layer that handles framing so what the sender and receiver both agree on the boundaries that constitute an app-level message.  Watson does this for you.

Please let me know if this helps answer your question or if I'm missing something.  Thanks, Joel

**Comment by pha3z** [comment]
Ok.  I think Simple TCP is exactly what I need.  The 3rd party client application I'm talking to already states that it sends data in blocks where each block starts with byte prefix indicating the block length and whether or not there is another block as a continuation of the current one.  When all the blocks are put together, it constitutes a completed transaction msg.  This sounds like the "Framing" you are talking about.

I actually already wrote all the code and unit tested it to do all this block-transaction msging for the 3rd party client. But I thought that was just a layer on top of everything else.  I didn't realize this meant I needed to use a special lower level TCP client without framing.

Thank you for your help!  I will try Simple TCP. :)

**Comment by pha3z** [comment]
I'm retooling my own Tcp abstraction to support Simple Tcp.  It looks like most of the code is a pretty simple mapping to move from Watson to Simple.

But I noticed I lose the built in IdleClientTimeoutSeconds. :(  Would it be a big deal to move this feature from Watson to SimpleTcp so they both have it?

**Comment by jchristn** [comment]
Nah, wouldn't be a big deal.  I'll add it to the list.  Could you open an issue/enhancement in the SimpleTcp repo so I can track it?  Thanks!  (closing this one)

**Comment by pha3z** [comment]
Just wanted to let you know Simple TCP worked with the 3rd party client. :) All I had to do was swap out Watson for SimpleTCP, and then stuff started working correctly. Just had to do a little framing debugging and it worked. Thank you!!
