### ISSUE TITLE
Problems with setting used hooks.

### ISSUE THREAD

**Issue by Crushedice** [jchristn/WatsonTcp#50]
Greetings.
So far it worked all fine, the new methods helped me out a lot, 
Made a custom "CurrentClient" class with additional info to be send with the metadata.

But as i went to  test run the first time i got some problems. Here a small recording, - explains better then words [http://dmt.ovh/images/webm/kloyZ.webm](url)

Also . - is there any way to enable both methods?
Stream with metadata  And  Message received ? 
in current code i used the Message received method as a sort of callback, as i only had a small string to send and no bigger stream or metadata. 

Thanks

**Comment by jchristn** [comment]
Hi @Crushedice glad it is working for you.  The reason only one of MessageReceived and StreamReceived can be set is because it dictates whether or not Watson reads the payload from the network:

- MessageReceived - WatsonTcp reads the message payload and passes it in a byte array to the callback
- StreamReceived - WatsonTcp does not read the message payload, but passes the content length and the stream to the callback, expecting your code to read the data

That's why only one can be used :)  The *WithMetadata methods rely on that same logic as well.  

Cheers,
Joel
