### ISSUE TITLE
Receiving messages from non-WatsonTcp server

### ISSUE THREAD

**Issue by developervariety** [jchristn/WatsonTcp#56]

**Comment by jchristn** [comment]
Hi @developervariety what's the issue?

**Comment by developervariety** [comment]
Thank you for the fast response.

I have a Golang application communicating with my C# application just fine, but when I send a message from Golang (using [tcp_server](https://github.com/firstrow/tcp_server)) my C# application (using WatsonTcp) it does not pick up the message.

**Comment by jchristn** [comment]
Hi @developervariety that is by design.  WatsonTcp uses a framing mechanism to make sure that when you send some n bytes of data, n bytes are received as an entire message on the other side.  It's essentially a messaging layer on top of TCP, meaning it can't work unless both sides are using that layer.

If you want something unmanaged, please check out SimpleTcp here: https://github.com/jchristn/simpletcp

It's also available on NuGet here: https://www.nuget.org/packages/SuperSimpleTcp/

It does NOT provide framing, meaning, there are no guarantees that if you send n bytes, n bytes will be received as a single autonomous message.  But, the upside is, any TCP client or server can communicate with it.  

Please let me know if any issues with it!  Cheers, Joel

**Comment by simonhaines** [comment]
Hi @jchristn, would you mind adding this information to the README (with the link to simpletcp)? I suspected some application-layer jiggery-pokery with the 'SendAndWait' method but it took me a good hour or so debugging before finally adding logging to my remote server, searching for this issue, etc. Cheers, Simon.

**Comment by jchristn** [comment]
Hi @simonhaines not a problem, that's a great suggestion.  I'll do that now.  Cheers

**Comment by jchristn** [comment]
This is done.

I also listed CavemanTcp first, since it is an even more primitive wrapper over TCP, exposing control over the number of bytes to read from the socket.
