### ISSUE TITLE
how to set TcpNoDelay true?

### ISSUE THREAD

**Issue by mzelecom** [jchristn/WatsonTcp#6]
Hi.
finally i can use your library in vb.net.
i used it for my game server.and i need to set TcpNoDelay to true .
how can i do that?
thanks

**Comment by jchristn** [comment]
Hi @mzelecom , I'm glad to hear you can use it!  If you'd like to enable NoDelay, you can do it by modifying the constructor in WatsonTcpClient.cs after ```Client = new TcpClient()```.  However, I'm not sure that NoDelay will help, since its main purpose is to force sending segments as they are received from the app in the send buffer (rather than packing them).  WatsonTcp is already doing that for you by taking byte array data from your app and packing it into a framed message which is then passed to TCP.  But, I may be missing your use case - let me know!

Also - since you're using VB, if you can describe the use case to me, I'll be happy to update the library to include the change for you so you don't have to do it.  

Thanks!

**Comment by mzelecom** [comment]
thank for replay.
i used watsontcp just for server .my clients are android devices.
Because my packets in server sometimes very small like 'igd' and i need to send it to client Instantly.
i think tcp send buffer must full to send it to client and i must have to set NoDelay true to force it send packets.

my game server just get some data from clients and store in mysql .it has chat room and Etc.

**Comment by jchristn** [comment]
Ah.  Are you implementing your clients in a way that mimics the framing used by WatsonTcp?  Both the client and server use a message framing layer which will affect what is sent over the network.

**Comment by mzelecom** [comment]
i could transmit data from client and watsontcp i know the frame is 'number of bytes : message '.its work.
if my frame not true watsontcp show time out and doesn't get message.

**Comment by jchristn** [comment]
Hi @mzelecom would you be willing to share the source code you're using to package the message and send?  I'm happy to take a look at it.

**Comment by mzelecom** [comment]
my code in vb.(basic4android)

Sub Send(msg As String)
	Dim Buffer() As Byte
	msg= msg  & Chr(13) & Chr(10)
	Buffer = msg.GetBytes("UTF8")
	msg=Buffer.Length  & ":" & msg
	Buffer = msg.GetBytes("UTF8")
	socket.Write(Buffer)
End Sub

**Comment by jchristn** [comment]
Can you try adding ```socket.Flush()``` after your call to ```socket.Write(Buffer)```?  It could be that TCP is waiting for additional data before flushing the send buffer, and what you want it to do is send the message immediately (i.e. flush the buffer).

**Comment by jchristn** [comment]
Hi @mzelecom any chance you were able to try this?
