### ISSUE TITLE
SendAndWait deadlock

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#80]
Hi, I'm experiencing some strange problems like a deadlock when the client and the server makes a SendAndWait call at the same time.

Even if the execution of methods completes in less than one second both receives a timeoutException.

I've tested and we fall in the deadlock even if the first request is sent by the client or the server indifferently.
If you want I can provide two program.cs to test the situation.

thanks
Michele

**Comment by jchristn** [comment]
Hi @ozrecsec so sorry for the delay in getting back to you.  I've had a really hectic week.  I put in a commit moments ago (see https://github.com/jchristn/WatsonTcp/commit/07b682b5e0cd4277260538353efb755219551b09) to test this scenario.  Please refer to the ```Test.Deadlock``` project.  I can't seem to reproduce what you are seeing.  Please let me know if I can amend my code in some way to better mimic what you are seeing.

Here's the output, as you can see requests and responses are going through fine with my test project.

```
C:\Code\Watson\WatsonTcp-4.1\Test.Deadlock\bin\Debug\netcoreapp3.1>Test.Deadlock
Server: [WatsonTcpServer] Starting on 127.0.0.1:8000
Client: [WatsonTcpClient] Connecting to 127.0.0.1:8000
Client: [WatsonTcpClient] Connected to server, starting data receiver
Client connected to server
Server: [WatsonTcpServer] Accepted connection from 127.0.0.1:53330
Server: [WatsonTcpServer] Starting data receiver for 127.0.0.1:53330
Client connected to server: 127.0.0.1:53330
Client received sync message from server: Here's your request from the server!
Server received sync message from client 127.0.0.1:53330: Here's your request from the client!
Client received response from server: Here's your response from the server!
Server received response from 127.0.0.1:53330: Here's your response from the client!
Client received sync message from server: Here's your request from the server!
Server received sync message from client 127.0.0.1:53330: Here's your request from the client!
Client received response from server: Here's your response from the server!
Server received response from 127.0.0.1:53330: Here's your response from the client!
Server received sync message from client 127.0.0.1:53330: Here's your request from the client!
Client received sync message from server: Here's your request from the server!
Client received response from server: Here's your response from the server!
Server received response from 127.0.0.1:53330: Here's your response from the client!
```

Again so sorry for taking so long to get back to you!!

**Comment by ozrecsec** [comment]
thank you for the response. I thought you're waiting my examples :-)

now I try your test and give you soon a response

**Comment by ozrecsec** [comment]
ok, I've tested with your Test.DeadLock and also with two new console projects (client and server) and works fine.
Then I've tested with two winforms projects and the problem come out... the problem is the main thread of the gui program... in my test I tried to call sendAndWait (in both client and server) in another thread and so works fine.

I think this is not a bug but who uses the library whitin a GUI project should know this "feature".

In my winform test you can send request from client or server without errors only if you make those in different times, if you make the two requests in less than 2 seconds you'll get the timeoutexception.... unless you check the checkbox  "manage communication in parallel thread" :-)

I attach my Test with winforms so you can see it with your eyes :-)

Have any idea how to resolve this inside the library insteadof bypass externally with threads?
 
many thanks for your time
Michele
 

[TestDeadlockWatson.zip](https://github.com/jchristn/WatsonTcp/files/4643384/TestDeadlockWatson.zip)

**Comment by jchristn** [comment]
Hi Michele, thanks for putting this together!  I see the issue; yes it is not recommended that synchronous/blocking code be placed in the main UI thread for Winform/WPF apps.  The app can become unresponsive and potentially cause background events to not fire because the main thread is blocked.  

The ```Send``` methods (not ```SendAndWait```) *also* have this issue because they are blocking/synchronous.  However, since they don't wait for a response, you may never notice the UI thread is blocked.

The ```SendAsync``` methods don't have this problem because they are asynchronous, as long as you use async/await syntax.

```SendAndWait``` was designed specifically to block, so the only way around it is really to run it in a background task.  

Under the hood WatsonTcp is using the same ```System.Net.Sockets``` that many others have used in Winforms/WPF projects and been bitten by this issue.  See https://stackoverflow.com/questions/22655111/asynchronous-sockets-blocking-ui-thread for an example.

I wish there was something I could do in the library to circumvent this, but if I did, I would be defeating the purpose of having a synchronous method that sends a request and blocks while waiting for a response.

Another way around this would be if you maintained a dictionary of requests you have sent (GUID in the metadata).  When you ```Send``` or ```SendAsync``` a request, send that GUID in the metadata, and add it to the local dictionary.  Then when a message comes in, look for that GUID, and if the GUID matches, you know it's a response to a request you sent earlier.  WatsonTcp is essentially doing that behind the scenes for ```SendAndWait```.  

Please let me know if you have any other thoughts on this!

Cheers, Joel

**Comment by ozrecsec** [comment]
Okay, I'm with you on the need to manage calls in separate threads.
I haven't seen what's under the hood yet, but I still have some doubts about the deadlock. But that doesn't hurt me :-)
I expected to block the application only for the duration of SendAndWait (about 2 seconds) and therefore the answer will return to the caller ... but even if I put the timeout at 60 seconds and the two simultaneous sendAndWait take two seconds to do the job the application hangs for 60 seconds and then throws the exception.

Maybe it is possible to run watsonTCP entirely in another thread? I do not know...
However this is not a real problem, it is only one aspect to consider when developing programs with a GUI.

second me you can close this problem

Thanks again!
cheers
Michele
