### ISSUE TITLE
Problem if SendAndWait called in Client_ServerConnected event

### ISSUE THREAD

**Issue by ozrecsec** [jchristn/WatsonTcp#81]
If I send a request with SendAndWait method inside the event ServerConnected the server receives the mnessage but the response will never come back to the client. the client hangs until the timeout and disconnects.

Do you ned an example to check?

bye
Michele

**Comment by jchristn** [comment]
Hi @ozrecsec looking into this tonight.  Thanks!

**Comment by jchristn** [comment]
I believe this is because the ServerConnected event fires before the DataReceiver is started.  I'm going to test it with a fix (and check to see if I need to fix it on both client and server).

![image](https://user-images.githubusercontent.com/1421081/82012096-c0c33480-962b-11ea-92be-ab5f477f72d6.png)

**Comment by jchristn** [comment]
Looks like server was already set up correctly.

![image](https://user-images.githubusercontent.com/1421081/82012261-3deea980-962c-11ea-9962-aa0ca95d89c9.png)

**Comment by jchristn** [comment]
Ok, I have a fix in.  Will build new version and publish shortly.

**Comment by jchristn** [comment]
Fix is in!  Please re-open if any issues.

NuGet: https://www.nuget.org/packages/WatsonTcp/4.1.11
Commit: https://github.com/jchristn/WatsonTcp/commit/535fcaa99b0155b61e46508ecdb392597471da12
