### ISSUE TITLE
Detecting abrupt connection loss due to unplugging network cable

### ISSUE THREAD

**Issue by jensvanhoof86** [jchristn/WatsonTcp#91]
Hi,
Fairly new to C# (and even github) so hoping I'm doing this correctly. If not, feel free to correct me!

So far, I've had good luck with the WatsonTCP project and disconnection scenarios due to either the server or the client going offline. I am checking on the client side if the connection with the server is working by using the "status" command. Whenever the server goes offline by closing the application the status at the client is successfully updated to false.

However, if the connection to the server is abruptly disconnected by unplugging the network cable, the response to a new "status" command will still be true, but (obviously) any communication attempt after that fails. It does automatically reconnect after a few seconds when the network cable is plugged in again.

Is this a known issue, and if so: is there a known workaround? Maybe I'm missing something obvious.
Thanks!!

**Comment by jchristn** [comment]
Hi @jensvanhoof86 thanks for your note.  There is, unfortunately, no clean solution to this.  There are APIs available underneath to check the status of the local network interface, however that doesn't do any good to notify a connected client if a server's network interface disconnects.

It is really up to the operating system to determine when to close underlying TCP connections when an adapter disconnects.  The problem is, if the network adapter is disconnected, those packets can't go out to properly terminate the connection on the other side.

The only workaround I know about in this case is having a heartbeat message exchange between nodes.  Even then, it's unreliable, because you don't want to disconnect after the loss of a single heartbeat (many reasons why a packet would be dropped or otherwise fail), so you'd really be optimizing between time zero and the time at which the operating system indicates that the connection has failed.

Cheers, Joel
